#pragma once
// Used by debug source
// and generated by "interrupt" thread
#include "stream_rtos_events.h"


#define AUDIO_SOURCE_FRAME_EVENT (1U << 0)
#define AUDIO_SOURCE_OVERFLOW_EVENT (1U << 1)

#define VIDEO_SOURCE_FRAME_EVENT (1U << 0)
#define VIDEO_SOURCE_EOS_EVENT (1U << 1)
#define SWITCH_EVENT (1U << 2)
