// This file is automatically generated. Do not edit.

#include <cstdint>
#include "app_config.hpp"
#include "stream_platform_config.hpp"
#include "cg_enums.h"
#include "StreamNode.hpp"
#include "cstream_node.h"
#include "IdentifiedNode.hpp"
#include "EventQueue.hpp"
#include "GenericNodes.hpp"


#include "nodes/EmptySource.hpp"
#include "nodes/NullSink.hpp"

template class EmptySource<q15_t,320>;
template CStreamNode createStreamNode(EmptySource<q15_t,320> &obj) ;
template class NullSink<q15_t,320>;
template CStreamNode createStreamNode(NullSink<q15_t,320> &obj) ;

// Selector initializations
