// This file is automatically generated. Do not edit.
#pragma once
extern template class VStreamAudioSource<sq15,320>;
extern template CStreamNode createStreamNode(VStreamAudioSource<sq15,320> &obj) ;
extern template class NullSink<sq15,320>;
extern template CStreamNode createStreamNode(NullSink<sq15,320> &obj) ;
