// This file is automatically generated. Do not edit.
#pragma once
extern template class EmptySource<q15_t,320>;
extern template CStreamNode createStreamNode(EmptySource<q15_t,320> &obj) ;
extern template class NullSink<q15_t,320>;
extern template CStreamNode createStreamNode(NullSink<q15_t,320> &obj) ;
